# Generated by Django 3.1.5 on 2021-02-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedometer',
        ),
    ]
