# Generated by Django 3.1.5 on 2021-02-26 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_delete_pedometer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps_counter', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(50000), django.core.validators.MinValueValidator(1)])),
                ('day', models.DateField(unique=True)),
            ],
        ),
    ]
