# Generated by Django 3.1.5 on 2021-02-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0003_daysteps'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
