# Generated by Django 3.1.5 on 2021-02-26 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0004_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysteps',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='steps.user'),
            preserve_default=False,
        ),
    ]
