# Generated by Django 3.1.5 on 2021-02-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0005_daysteps_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='daysteps',
            unique_together={('user', 'day')},
        ),
    ]
