# Generated by Django 3.1.5 on 2021-02-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0006_auto_20210226_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysteps',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='daysteps',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='daysteps',
            constraint=models.UniqueConstraint(fields=('user', 'day'), name='unique chapter'),
        ),
    ]
